local g = vim.g
local o = vim.opt

o.swapfile = true
o.termguicolors = true
o.smartcase = true
g.mapleader = " "
o.laststatus = 3
o.hlsearch = true
o.incsearch = true
o.ignorecase = true
o.relativenumber = true
o.number = true
o.wrap = false
o.clipboard = "unnamedplus"
o.encoding = "utf-8"
o.tabstop = 4
o.shiftwidth = 4
o.expandtab = true
o.termguicolors = true
o.mouse = "a"
o.splitbelow = true
o.splitright = true
o.scrolloff = 9
o.cursorline = true
o.scroll = 6
o.signcolumn = "yes"
o.pumheight = 16
o.winborder = "single"
o.langmap =
	[[ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz]]
